// <auto-generated />
using System;
using BlazorChatDB.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorChatDB.Server.Migrations
{
    [DbContext(typeof(Baza))]
    partial class BazaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlazorChatDB.Shared.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Sifra")
                        .HasColumnType("text");

                    b.Property<DateTime>("UclanioSe")
                        .HasColumnType("datetime");

                    b.Property<string>("Uname")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Korisniks");
                });
#pragma warning restore 612, 618
        }
    }
}
